### PR TITLE
Fix build on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by pbst**
cherry-picked the commit https://github.com/abiondo/afl/commit/eef10fbf6b259ccdaa2b205c6eeb0c2db83d4a46

### CODE REVIEW

**Comment by zardus** [comment]
It's better to just rebase on a modern AFL or, better yet, make our AFL setup process less dumb. @gokulkrishna, can you work your magic on this repo (in combination with https://github.com/shellphish/shellphish-afl) as well?

**Comment by pbst** [comment]
This seems to be related to Issue #3. Is someone working on this?

**Comment by gokulkrishna01** [comment]
This is fixed

**Comment by zardus** [comment]
Years later, this can be closed! This repo has been obsoleted by build process updates in shellphish-afl.

**Pull request closed without merging**
